### ISSUE TITLE
i3 covered by desktop background (?) and cinnamon panel missing

### ISSUE THREAD

**Issue by LiSongMWO** [Gigadoc2/i3-cinnamon#4]
I've used your scripts on a gentoo machine, the session appears in the session list in lightdm and I can login to it. However when I do, only the background from lightdm is displayed. No cinnamon panel, no i3. 

But the I know that i3 is running because i can operate it blindly and the cursor icon changes as I move it over where I know my auto started programs are and I can open a terminal and touch a file which i can then verify exists from a tty. I also see from my i3 logs that it started. 

It feels like the background bitmap is drawn over everything but this doesn't quite add up as its the background from my lightdm, not the one I set in cinnamon.

Do you have any suggestions as to what might be causing this?

**Comment by Gigadoc2** [comment]
I can't really reproduce what you are describing, but it does sound like a rendering error somewhere.

What greeter are you using for lightdm? What graphics driver, and do you have a compositor starting with i3?

By the way, the cinnamon panel will not appear in i3-cinnamon. The desktop will look just like i3 (except with the background set by cinnamon-session), but the settings-daemon will run in the background and do it's various kinds of magic (setting GTK theme details, managing input device settings, etc.).

AFAIK the cinnamon panel is part of the window manager, similar to how gnome-shell works, so we cannot use it with i3 :(

**Comment by LiSongMWO** [comment]
I found the culprit, it seems to have been the latest chrome update (I auto launch it from i3) which coincided with me installing cinnamon and trying this which seems to have hung the rendering somehow. I found this by dropping to tty after logging in and discovering two hanging cat processes started by chrome and removing chrome from my auto start fixed it.

Yeah I also found out that the cinnamon WM and panel are integrated so this whole thing didn't do what I wanted anyway ¯\_(ツ)_/¯ I'm trying to get all the modern conveniences of cinnamon with the bar and menu and settings panel for discovering apps and hardware etc but with a tiling WM and keyboard focused navigation as an option.

**Comment by Gigadoc2** [comment]
Yeah, I'd like that as well, but unfortunately this does not seem to be possible with currently existing software.

If it is application launching (in modern desktop style instead of execing binaries) then maybe https://github.com/DaveDavenport/rofi is for you. At least, that's what I am using for launching applications (with the Destkop File Application Launcher).

Also, there are some panels with menus (and even desktop switchers) that might work. lxqt-panel is one I can think of, and it also has an application launcher menu.

**Comment by LiSongMWO** [comment]
Yeah, I'm using Mate with i3 and it is working OK but the panel needs work and the applets are inconsistent and some other annoyances which is why I pinned my hopes on Cinnamon but alas... I'm at the point of maybe just fixing the mate panel but I don't really have the time between work and other projects
